### ISSUE TITLE
Not respawning on death

### ISSUE THREAD

**Issue by Haidee-hm** [fivem-ex/esx_kashacter#1]
When I die, my character will not respawn (don't have esx_ambulancejob).

I have disabled esx_kashacters to test this and respawn correctly on death.

With esx_kachacters enabled again, I cannot respawn after death.

Using latest versions of all scripts including es_extended at the time of this post.

**Comment by RikoDEV** [comment]
Should the player respawn immediately after death?

**Comment by RikoDEV** [comment]
Can you remove [this code](https://github.com/fivem-ex/esx_kashacter/blob/master/esx_kashacters/client/main.lua#L80) from your `client/main.lua` and test it?

**Comment by Haidee-hm** [comment]
Many thanks RikoDev  :-) 
Respawning after death now working with the code fix you provided.
