### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by rayyanallaf** [fivem-ex/esx_kashacter#10]
in the users table your characters don't load in due to `:` missing in `Char19bcbe48032443b6561a06c355bef87ee50d0da03` Shouldn't it be like `Char1:9bcbe48032443b6561a06c355bef87ee50d0da03`.

Also, I have newest kashacters installed with all the new patches

My license inserts correctly in the user's table `license:9bcbe48032443b6561a06c355bef87ee50d0da03` just not my character licenses.

**Comment by RikoDEV** [comment]
Try latest version. :)

https://github.com/fivem-ex/esx_kashacter/pull/8/commits/220f21db35037f7cc865b4d504735f1bd3cdbdd1
