### ISSUE TITLE
attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by KoolAiddTV** [fivem-ex/esx_kashacter#12]
Getting an error on the server console: https://prnt.sc/roc2zs
Is the function: https://prnt.sc/roc3n2
Is the handler: https://prnt.sc/roc3u9
I have the users table updated with the latest esx. Not sure why it's not finding the coords. Any idea?

**Comment by KoolAiddTV** [comment]
Resource name. Ignore me.

**Comment by SlomGom** [comment]
Hey!

I get the same error and have made all changes according to the instructions. Am I doing something wrong?

**Comment by SotaRex** [comment]
same

**Comment by RikoDEV** [comment]
https://github.com/fivem-ex/esx_kashacter/issues/15
