### ISSUE TITLE
stuck on floating above the city

### ISSUE THREAD

**Issue by GewoonMarlon** [fivem-ex/esx_kashacter#18]
When i click on the character create button I just keep floating above the city.
No regsiter screen nothing??

Anyone have a fix or can help me out?
![Screenshot_30](https://user-images.githubusercontent.com/47403510/79046442-4872e900-7c11-11ea-9213-d3b9722e6435.png)

**Comment by MontyDriver** [comment]
I have this but I don't see the characters to being with when I load in all I see is a blank floating above the city screen

**Comment by RikoDEV** [comment]
This seems like an error in getting the player spawn position from the database.

https://github.com/fivem-ex/esx_kashacter/issues/15

**Comment by GewoonMarlon** [comment]
Yes i know for some reason my es_extended keeps asking for a table that is called: coords
But i dont have any table of that kind, is er any way to implement the coords table and how to do this?

![image](https://user-images.githubusercontent.com/47403510/79204792-645ad280-7e3d-11ea-8077-b5bafcdfc295.png)

**Comment by RikoDEV** [comment]
https://github.com/ESX-Org/es_extended/blob/master/es_extended.sql
