### ISSUE TITLE
Characters Not Saving

### ISSUE THREAD

**Issue by Natedawg63** [fivem-ex/esx_kashacter#27]
I am starting with a fresh server and files, so all of my ESX Org files are the most recently updated, every single one they offer for download. I edited all the es ext .lua's per the instructions. i can create a character, but then i fly back into the city, there is no 1st character to choose, even tho it is saved in the database. also having problems spawning at 'last position' - but i may have that sorted after altering the user 'position' format. can't for the life og me to get characters to show in reflight tho.

thanks...
Nate

**Comment by RikoDEV** [comment]
https://github.com/fivem-ex/esx_kashacter/issues/15
