### ISSUE TITLE
Black Screen Position Issue.

### ISSUE THREAD

**Issue by rayyanallaf** [fivem-ex/esx_kashacter#28]
kashacters was working for me perfectly find and then a new update came out and a new es_extended and then this is when it went downhill. So when I select a character the character goes into a black screen that infinitely loads. I've reinstalled esx_kashacters several times, I've done all the steps correctly. My console gives an error which is: https://imgur.com/CqrBQvM

This a Getspawn Position error. I've tried going back to old versions and even tried only replacing the spawning function. Nothing has worked for me so far. does anyone know why this is happening.

**Comment by RikoDEV** [comment]
https://github.com/fivem-ex/esx_kashacter/issues/15
