### ISSUE TITLE
No characters to select

### ISSUE THREAD

**Issue by KoolAiddTV** [fivem-ex/esx_kashacter#4]
Everything works besides when going to select a character it always just says Create new character. Doesn't seem to be giving any errors either

**Comment by RikoDEV** [comment]
Read all points of readme and change function in your es_extended files.

**Comment by KoolAiddTV** [comment]
Thanks man

**Comment by TheTrueUprising** [comment]
> Read all points of readme and change function in your es_extended files.
cannot find any of the code that you said needed changing in es_extended
